### ISSUE TITLE
Fuzzywuzzy module

### ISSUE THREAD

**Issue by moorets1** [karl-sc/cg-auto-bind-interface-zone#1]
What does this module mean

PS C:\CloudGenix_Python\cg-auto-bind-interface-zone-main> py cg-auto-bind-interface-zone.py --zonename zscaler --interface-match sl-zscaler
Traceback (most recent call last):
  File "C:\CloudGenix_Python\cg-auto-bind-interface-zone-main\cg-auto-bind-interface-zone.py", line 25, in <module>
    **from fuzzywuzzy import fuzz, process
**ModuleNotFoundError: No module named 'fuzzywuzzy'****

**Comment by karl-sc** [comment]
Hi, this means you are missing the required python module named 'fuzzywuzzy' found here: https://pypi.org/project/fuzzywuzzy/

you can install it with the pip command which could be one of the following depending on your environment:
1) pip install fuzzywuzzy
2) python3 -m pip install fuzzywuzzy
3) pip3 install fuzzywuzzy
